check for existing user and catch error message
ProSchedule-Manager/user-permissions-app pull request #2
Opened 2024-05-24 16:52 UTC by RianRBPS

Neste PR eu acrescente três validações para a função creatUser, sendo elas

- Checar se o email é válido

- Verificar se o email já está em uso

- Confirmar que nenhum campo está nulo

E além disso alterei a língua da mensagem de erro para português

2024-05-24 18:15 UTC, vinicius5581 reviewed
Looks good. Added a few comments.

2024-05-24 18:15 UTC, vinicius5581 commented on controllers/userControllers.js
> +
Add validation for required fields:
```
// Validate required fields
    if (!req.body.email || !req.body.password || !req.body.permission) {
      return res.status(400).json({ message: "Missing required fields: email, password, or permission" });
    }
```


Add email validation (This can also be done on the model when using sequelize). 
```
// Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(req.body.email)) {
      return res.status(400).json({ message: "Invalid email format" });
    }
```

2024-05-24 18:15 UTC, vinicius5581 commented on controllers/userControllers.js
> +      return res.status(400).json({ message: "Email já se encontra em uso "});
Please write messages in english: `message: "Email is already in use"`

2024-05-24 18:15 UTC, vinicius5581 commented on controllers/userControllers.js
> +    res.send(submitedUser);
Let's return status code 201. Please see attached bellow:

```
res.status(201).json(newUser);
```
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

2024-05-24 18:15 UTC, vinicius5581 commented on controllers/userControllers.js
> +    const submitedUser = await database.User.create({
I would add a comment above this code block saying

```
// Create the new user
```

Also, let's rename `submitedUser` to `newUser`.

2024-05-24 18:15 UTC, vinicius5581 commented on controllers/userControllers.js
> +    console.error(error);
If adding `console.log`, its always a good idea to add a description to help identify it later on the console.


```
console.error("Error creating user:", error);
```

2024-05-24 18:15 UTC, vinicius5581 commented on controllers/userControllers.js
> +    res.status(500).json({ message: error.message })
This is not wrong, but assuming that the user of the api can't do much here, let's simply return a string here:

`res.status(500).json({ message: "Internal server error" });`

2024-05-24 23:56 UTC, RianRBPS commented on controllers/userControllers.js
> +
Invalid characters
![image](https://github.com/ProSchedule-Manager/user-permissions-app/assets/82774034/5250983f-e12f-438a-969e-e62d6a9404a3)

Email already in use
![image](https://github.com/ProSchedule-Manager/user-permissions-app/assets/82774034/3a0782e9-60cb-4cba-bd55-1cfbf4114ce1)

Missing requirements
![image](https://github.com/ProSchedule-Manager/user-permissions-app/assets/82774034/ccaf73ab-629b-4b09-b775-3b7b4471de6d)

2024-05-24 23:58 UTC, RianRBPS commented on controllers/userControllers.js
> +      return res.status(400).json({ message: "Email já se encontra em uso "});
Done

2024-05-25 03:20 UTC, vinicius5581 requested changes

2024-05-25 03:20 UTC, vinicius5581 commented on controllers/userControllers.js
> +    res.status(201).json(newUser);
Acredito que sua aplicação deva ter quebrado com esta linha. Vc nao definiu `newUser` em lugar nenhum. 

No comentario eu sugeri mudar `const submitedUser = await database.User.create({` para `const newUser = await database.User.create({` o que nao foi feito e logo `newUser` nunca foi definido. 

Alem disto agora vc tem :

```
res.status(201).json(newUser);
res.send(submitedUser);
```

Deveria ser so :

```
res.status(201).json(newUser);
```

2024-05-25 03:21 UTC, vinicius5581 commented on controllers/userControllers.js
> +    const submitedUser = await database.User.create({
??

2024-05-27 20:43 UTC, vinicius5581 commented on controllers/userControllers.js
> +    res.send(submitedUser);
test

2024-05-27 20:44 UTC, vinicius5581 reviewed
test

2024-05-27 20:44 UTC, vinicius5581 commented on controllers/userControllers.js
> +    const submitedUser = await database.User.create({
Test

2024-05-27 20:44 UTC, vinicius5581 commented on controllers/userControllers.js
> +    res.status(201).json(newUser);
test

2024-05-27 20:45 UTC, vinicius5581 commented on controllers/userControllers.js
> +    res.status(201).json(newUser);
test

2024-05-27 20:46 UTC, RianRBPS reviewed
teste

2024-05-27 20:46 UTC, RianRBPS commented on controllers/userControllers.js
> +    res.status(201).json(newUser);
De fato eu não me atentei a isso, eu adotei agora a mudança sugerida não feita e as requisições voltaram a funcionar

2024-05-27 20:46 UTC, RianRBPS commented on controllers/userControllers.js
> +    res.send(submitedUser);
Alright, I'm also reading a few of the other status code. 

Should there also be an status code for the READ, UPDATE & DELETE success operations?

2024-05-27 22:11 UTC, vinicius5581 requested changes

2024-05-27 22:11 UTC, vinicius5581 commented on controllers/userControllers.js
> +    console.error("Error creating user:", error);
Move this inside the catch.

2024-05-27 22:15 UTC, vinicius5581 approved these changes
LGTM

2024-05-28 00:50 UTC, merged