Rian/unit test
ProSchedule-Manager/user-permissions-app pull request #5
Opened 2024-05-29 19:19 UTC by RianRBPS

- Fixed a typo in userController which caused "catch" to not work properly

- Created userController.test.js

- All the five tests are properly working, being those the following:

2024-05-29 19:21 UTC, RianRBPS commented
![image](https://github.com/ProSchedule-Manager/user-permissions-app/assets/82774034/79ecbc23-cd45-402a-9233-dff572c5e478)

2024-05-29 19:30 UTC, vinicius5581 requested changes
Quando usando jest vc nao precisa de sinon. Vamos trabalhar com jest. No slack ontem eu tb apontei melhores nomes para os seus testes:


- creates a new user
- handles email already in use
- handles missing required fields
- handles invalid email format

2024-05-29 19:30 UTC, vinicius5581 commented on controllers/userControllers.js
>      res.status(500).json({ message: err.message });
Vc vai ter um erro aqui. Vc esta passando o parametro como `error` em `} catch (error) {` e o usando como `err` em `message: err.message`.  Voce pode chamar o parametro do que quiser, `err`, `error` ou ate mesmo `aviao`, desde que use o mesmo. No caso se vc rodar a sua funcao ai, deve aparecer um erro dizendo que `err` esta undefined.

2024-05-29 19:30 UTC, vinicius5581 commented on package.json
>      "nodemon": "^3.1.0",
Vamos mover `nodemon` para `devDependencies`. A razao e pq ele so e usado durante development e nao precisa dele quando a aplicacao estiver deployed em producao. No caso em producao vamos rodar com `node app.js`.

2024-05-29 19:30 UTC, vinicius5581 commented on tests/userController.test.js
> +// userController.test.js
Remover comentarios.

2024-05-29 19:30 UTC, vinicius5581 commented on tests/userController.test.js
> +const sinon = require('sinon');
Como falamos ontem, vc nao precisa de sinon quando usando jest. Se ainda tiver duvidas, podemos marcar uma conversa. Deixe eu saber.

2024-05-29 19:35 UTC, RianRBPS commented on controllers/userControllers.js
>      res.status(500).json({ message: err.message });
Entendido e alterado

2024-05-29 19:36 UTC, RianRBPS commented on package.json
>      "nodemon": "^3.1.0",
Done

2024-05-29 19:36 UTC, RianRBPS commented on tests/userController.test.js
> +// userController.test.js
Feito

2024-05-29 19:38 UTC, RianRBPS commented on tests/userController.test.js
> +const sinon = require('sinon');
Me esqueci de remover a requisição, sem dúvidas por enquanto

2024-05-29 19:40 UTC, RianRBPS commented
Resolvi as suas observações

2024-05-29 19:50 UTC, vinicius5581 commented
> Resolvi as suas observações

Os testes ainda estao escritos com `sinon`.  Vc nao precisa de `sinon` ja que o `jest` ja tem sua propria biblioteca de mocks e assertions.

2024-05-29 20:31 UTC, RianRBPS commented
Refiz os testes, algum problema está acontecendo que os testes `handles missing required fields` e `handles invalid email format` só passaram quando eu coloquei o bloco de códigos deles acima do teste `handles email already in use`.

Quando os dois testes em questão ficavam abaixo do `handles email already in use`, os testes falhavam e tinham como retorno a mensagem de que o email já estava em uso (que é do teste que handle o email)
![image](https://github.com/ProSchedule-Manager/user-permissions-app/assets/82774034/1ec422c3-c65a-4709-b462-99e523b70270)

2024-05-29 21:20 UTC, vinicius5581 commented
> Refiz os testes, algum problema está acontecendo que os testes `handles missing required fields` e `handles invalid email format` só passaram quando eu coloquei o bloco de códigos deles acima do teste `handles email already in use`.
> 
> Quando os dois testes em questão ficavam abaixo do `handles email already in use`, os testes falhavam e tinham como retorno a mensagem de que o email já estava em uso (que é do teste que handle o email) ![image](https://private-user-images.githubusercontent.com/82774034/334957170-1ec422c3-c65a-4709-b462-99e523b70270.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMTcxODYsIm5iZiI6MTcxNzAxNjg4NiwicGF0aCI6Ii84Mjc3NDAzNC8zMzQ5NTcxNzAtMWVjNDIyYzMtYzY1YS00NzA5LWI0NjItOTllNTIzYjcwMjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDIxMDgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNGJkZjc4MDBiNDdlMDYwNWJkM2VlMTYxYjQ4OWIzZGUzMTUzZWMwMzBiYjMxOWY0ZWMwZjM1MWZmYmIwYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuNwmyunEuzwtX0G5kPen9q95l4z2ThDZodyUAElhMk)

Seus testes estao licking data. Provavelmente pq vc esta interagindo com o banco de dados no seu teste. 

Minha sugestao e que voce faca um mock do database. 

```
const { createUser, readUser, updateUser, deleteUser } = require('../controllers/userController');
const database = require('../models/User');

jest.mock('../models/User');

describe('User Controller', () => {
  let req, res;

  beforeEach(() => {
    req = {
      body: {},
      params: {},
    };
    res = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn().mockReturnThis(),
    };
  });

  describe('createUser', () => {

    ...

    it('handles email already in use'', async () => {
      req.body.email = 'test@example.com';
      req.body.password = 'password123';
      req.body.permission = 'user';

      database.User.findOne.mockResolvedValue(true);

      await createUser(req, res);

      expect(res.status).toHaveBeenCalledWith(400);
      expect(res.json).toHaveBeenCalledWith({ message: 'Email already in use' });
    });

    ...
  }

  describe('readUser', () => {
      ...
  }

  ...
}
```

2024-05-30 18:53 UTC, RianRBPS commented
O bloco de código referente ao 'User controller' está correto?

![image](https://github.com/ProSchedule-Manager/user-permissions-app/assets/82774034/3b32ecff-9137-4be0-a719-6ad3a3d6f4b8)

2024-06-04 17:57 UTC, RianRBPS commented
Please review

2024-06-05 00:04 UTC, vinicius5581 commented
This PR is becoming very messy. Let's break it down in multiple PRs to avoid confusion:

- [ ] rian/setup-jest-nodemon
- [ ] rian/routes-prefix
- [ ] rian/create-user
- [ ] rian/update-user

See my reply on slack for more context.

2024-06-10 16:59 UTC, closed without merging